import "@uploadthing/react/styles.css";
import "./globals.css";

import { ModalProvider } from "@/components/providers/modal-provider";
import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import ToasterProvider from "@/components/providers/toasterProvider";

const font = Open_Sans({
  subsets: ["latin"],
  // weight: ["200", "300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <ModalProvider />
        <ToasterProvider />
        {children}
      </body>
    </html>
  );
}
